"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const Users_controller_1 = require("./Users.controller");
const auth_1 = require("../../utils/auth");
const router = (0, express_1.Router)();
router.route("/signUp").post(Users_controller_1.signUp);
router.route("/logIn").post(Users_controller_1.signIn);
router.route("/").get(auth_1.auth, Users_controller_1.list);
router.route("/").put(auth_1.auth, Users_controller_1.update);
router.route("/").delete(auth_1.auth, Users_controller_1.destroy);
exports.default = router;
