"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const adPet_controller_1 = require("./adPet.controller");
const auth_1 = require("../../utils/auth");
const formData_1 = require("../../utils/formData");
const router = (0, express_1.Router)();
router.route("/").post(auth_1.auth, formData_1.formData, adPet_controller_1.create);
router.route("/adm/:petitionId").post(auth_1.auth, adPet_controller_1.adminApproval);
router.route("/adm").get(auth_1.auth, adPet_controller_1.listAllAdPets);
exports.default = router;
